# Generated by Django 5.0 on 2023-12-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend', '0002_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('firstNameLetter', models.CharField(max_length=1)),
                ('lastNameLetter', models.CharField(max_length=1)),
            ],
        ),
    ]
